const meiliClient = require("@src/Services/Meilisearch/MeilisearchClient");
const mysql = require("@src/Services/MySQL/MySQLClient");
const getListModules = require("@src/Api/getListModules");

const safeIdent = (s) => typeof s === "string" && /^[A-Za-z0-9_]+$/.test(s);

// ====== Main Handler ======
const getRecordIdByNo = async (req, res, redis) => {
  try {
    const { noNum, module, filter = [] } = req.body || {};
    const userRole = req?.userRole;
    if (!noNum || !module || !userRole) {
      return res.status(400).json({ success: false, error: "Missing params" });
    }

    const raw = await redis.hget(`ERP:ModuleInfo:${userRole}`, module);
    if (!raw) {
      return res.status(404).json({ success: false, error: "Module not found" });
    }

    const { fields = [], table } = JSON.parse(raw) || {};
    const noNumField = fields.find(f => f?.type?.uitype == "4");
    const idField    = fields.find(f => f?.type?.name == "autogenerated");

    if (!table || !noNumField || !idField || table !== noNumField?.table) {
      return res.status(400).json({ success: false, error: "Invalid module fields" });
    }

    const idCol = idField?.column || idField?.label;
    const noCol = noNumField?.column || noNumField?.label;

    if (![table, idCol, noCol].every(safeIdent)) {
      return res.status(500).json({ success: false, error: "Unsafe identifier" });
    }

    const sql = `SELECT \`${idCol}\` AS id FROM \`${table}\` WHERE \`${noCol}\` = ? LIMIT 1`;
    const rows = await mysql.query(sql, [noNum]);
    
    if(rows?.[0]?.id){
        const newReq = { ...req, body: { module, isRelatedList: true, filter: [`crmid = ${rows?.[0]?.id}`, ...filter] }, isGetOnlyData: true };
        const ListDatas = await getListModules(newReq, res, redis);
        const dataItem = ListDatas?.data?.hits?.[0];
        
        return res.status(200).json({ success: true, data: dataItem ?? null });
    }

    return res.status(200).json({ success: true, data: null });
  } catch (err) {
    return res.status(500).json({ success: false, error: err?.message || "Internal Server Error" });
  }
};

module.exports = getRecordIdByNo;

